-- Inserir produtos de exemplo para INT TOOLS
-- Execute este SQL no Supabase → SQL Editor

INSERT INTO products (
  name, slug, description, short_desc, price, old_price, stock, category_id,
  brand, model, voltage, power, warranty, active, featured, created_at, updated_at
) VALUES
  -- Ferramentas Manuais (category_id = 1)
  (
    'Jogo de Chaves Combinadas 12 Peças',
    'jogo-chaves-combinadas-12-pecas',
    'Jogo completo de chaves combinadas com 12 peças, fabricadas em aço cromo vanádio. Acabamento cromado para maior durabilidade e resistência à corrosão. Ideal para uso profissional e doméstico.',
    'Jogo completo com 12 chaves de 6mm a 22mm em aço cromo vanádio',
    149.90,
    NULL,
    45,
    1,
    'Tramontina',
    '44480112',
    NULL,
    NULL,
    '12 meses',
    true,
    true,
    NOW(),
    NOW()
  ),
  (
    'Alicate Universal 8 Polegadas',
    'alicate-universal-8-polegadas',
    'Alicate universal profissional de 8 polegadas com cabo emborrachado para maior conforto e isolamento elétrico até 1000V. Ideal para corte, dobra e preensão.',
    'Alicate universal 8" com cabo isolado 1000V',
    45.90,
    59.90,
    120,
    1,
    'Gedore',
    '8001-200',
    NULL,
    NULL,
    '24 meses',
    true,
    true,
    NOW(),
    NOW()
  ),
  (
    'Kit de Ferramentas 100 Peças',
    'kit-ferramentas-100-pecas',
    'Kit completo com 100 peças incluindo chaves de fenda, alicates, martelo, trena, nível, soquetes e muito mais. Acompanha maleta plástica resistente para organização e transporte.',
    'Kit completo 100 peças com maleta',
    289.90,
    349.90,
    28,
    1,
    'Stanley',
    'STMT74101',
    NULL,
    NULL,
    '12 meses',
    true,
    false,
    NOW(),
    NOW()
  ),

  -- Ferramentas Elétricas (category_id = 2)
  (
    'Furadeira de Impacto 1/2" 850W',
    'furadeira-impacto-850w',
    'Furadeira de impacto profissional com 850W de potência, mandril de 1/2 polegada, velocidade variável e reversível. Ideal para furar concreto, metal e madeira. Inclui maleta, jogo de brocas e manual.',
    'Furadeira de impacto 850W com maleta e acessórios',
    349.90,
    NULL,
    67,
    2,
    'Bosch',
    'GSB 13 RE',
    '220V',
    '850W',
    '12 meses',
    true,
    true,
    NOW(),
    NOW()
  ),
  (
    'Parafusadeira/Furadeira sem Fio 12V',
    'parafusadeira-furadeira-12v',
    'Parafusadeira/furadeira a bateria de 12V com 2 baterias de lítio, carregador bivolt automático, maleta e kit de bits. Leve e compacta, perfeita para trabalhos residenciais e profissionais.',
    'Parafusadeira 12V com 2 baterias e maleta',
    459.90,
    549.90,
    42,
    2,
    'Makita',
    'DF330DWE',
    'Bateria 12V',
    NULL,
    '12 meses',
    true,
    true,
    NOW(),
    NOW()
  ),
  (
    'Esmerilhadeira Angular 4.1/2" 850W',
    'esmerilhadeira-angular-850w',
    'Esmerilhadeira angular de 4.1/2 polegadas com motor de 850W, velocidade de 11.000 rpm, empunhadura lateral e trava de segurança. Ideal para corte e desbaste de metais.',
    'Esmerilhadeira 4.1/2" 850W profissional',
    229.90,
    NULL,
    55,
    2,
    'DeWalt',
    'DWE4120',
    '220V',
    '850W',
    '12 meses',
    true,
    false,
    NOW(),
    NOW()
  ),

  -- Equipamentos de Segurança (category_id = 4)
  (
    'Capacete de Segurança com Carneira',
    'capacete-seguranca-carneira',
    'Capacete de segurança classe B em polietileno de alta densidade com carneira ajustável. Proteção contra impactos e choques elétricos. Certificado CA aprovado pelo MTE.',
    'Capacete classe B com carneira ajustável CA aprovado',
    34.90,
    NULL,
    150,
    4,
    'Vonder',
    '7041340000',
    NULL,
    NULL,
    '6 meses',
    true,
    false,
    NOW(),
    NOW()
  ),
  (
    'Óculos de Proteção Incolor Anti-Embaçante',
    'oculos-protecao-incolor',
    'Óculos de segurança com lentes em policarbonato incolor, tratamento anti-risco e anti-embaçante. Proteção UV. Hastes ajustáveis para maior conforto. CA aprovado.',
    'Óculos anti-embaçante com proteção UV - CA aprovado',
    18.90,
    24.90,
    200,
    4,
    '3M',
    '2720',
    NULL,
    NULL,
    '12 meses',
    true,
    false,
    NOW(),
    NOW()
  ),

  -- Medição e Nivelamento (category_id = 6)
  (
    'Trena Profissional 5m x 25mm',
    'trena-profissional-5m',
    'Trena de 5 metros com largura de 25mm, fita em aço carbono com revestimento nylon para maior durabilidade. Trava automática, clip para cinto e nível de bolha integrado.',
    'Trena 5m com trava e nível de bolha',
    42.90,
    NULL,
    88,
    6,
    'Tramontina',
    '43155105',
    NULL,
    NULL,
    '12 meses',
    true,
    false,
    NOW(),
    NOW()
  ),
  (
    'Nível a Laser Automático com Tripé',
    'nivel-laser-automatico-tripe',
    'Nível a laser auto-nivelante com alcance de até 30 metros, 3 linhas laser (2 verticais e 1 horizontal), base magnética e tripé ajustável. Inclui óculos de visualização e maleta.',
    'Nível laser 3 linhas com tripé e maleta',
    389.90,
    479.90,
    22,
    6,
    'Skil',
    '0516',
    'Bateria 3xAA',
    NULL,
    '12 meses',
    true,
    true,
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
